[package]
name = "rusted-dectris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rusted_dectris"
crate-type = ["cdylib"]

[[bin]]
name = "rusted-dectris"
path = "src/main.rs"

[dependencies]
bincode = "1.3.3"
clap = { version = "3.2.16", features = ["derive"] }
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
memmap2 = "0.5.6"
pyo3 = { version = "0.16.5", features = ["extension-module"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
spin_sleep = "1.1.1"
zmq = "0.9.2"

[profile.release]
debug = true
